#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Executando verificação de segurança..."
npm run check:secrets

echo "✨ Executando lint-staged..."
npx lint-staged

echo "🔎 Executando type-check..."
pnpm type-check
