name: Project Automation

on:
  issues:
    types: [opened, assigned, closed, reopened]
  pull_request:
    types: [opened, closed, merged]
  issue_comment:
    types: [created]

jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/oldmoneygit/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move to In Progress on PR open
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const issueNumbers = body.match(/#(\d+)/g) || [];
            
            for (const issueRef of issueNumbers) {
              const issueNumber = issueRef.substring(1);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '🔄 PR opened: Work in progress'
              });
            }

      - name: Move to Done on PR merge
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const issueNumbers = body.match(/#(\d+)/g) || [];
            
            for (const issueRef of issueNumbers) {
              const issueNumber = issueRef.substring(1);
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: 'closed'
              });
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '✅ Completed via PR #' + pr.number
              });
            }

      - name: Detect blockers
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            if (comment.includes('blocked') || comment.includes('blocker')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: ['⚠️ blocker']
              });
            }
